# Generated by Django 5.0.6 on 2026-02-21 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("location_id", models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="AnomalyPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(db_index=True)),
                ("metric", models.CharField(max_length=32)),
                ("value", models.FloatField()),
                ("score", models.FloatField()),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="weather.city"
                    ),
                ),
            ],
            options={
                "ordering": ["-time"],
                "unique_together": {("city", "time", "metric")},
            },
        ),
        migrations.CreateModel(
            name="ForecastPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_time", models.DateTimeField(db_index=True)),
                ("yhat_temp_c", models.FloatField()),
                ("model_name", models.CharField(default="rf_lag", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="weather.city"
                    ),
                ),
            ],
            options={
                "ordering": ["-target_time"],
                "unique_together": {("city", "target_time", "model_name")},
            },
        ),
        migrations.CreateModel(
            name="WeatherRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("obs_time", models.DateTimeField(db_index=True)),
                ("temp_c", models.FloatField(blank=True, null=True)),
                ("humidity", models.FloatField(blank=True, null=True)),
                ("precip_mm", models.FloatField(blank=True, null=True)),
                ("wind_kph", models.FloatField(blank=True, null=True)),
                ("pressure_hpa", models.FloatField(blank=True, null=True)),
                ("source", models.CharField(default="qweather", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="weather.city"
                    ),
                ),
            ],
            options={
                "ordering": ["-obs_time"],
                "unique_together": {("city", "obs_time")},
            },
        ),
    ]
